export const actionTypes = {
    DO_LOGIN:'DO_LOGIN',
    CREATED_ACCOUNT:'CREATED_ACCOUNT',
    USER_SAVED:'USER_SAVED',
    DISPLAY_ERROR:'DISPLAY_ERROR',
    DISPLAY_SUCCESS:'DISPLAY_SUCCESS',
    CATEGORY_SAVED:'CATEGORY_SAVED',
    CATEGORY_LOADED:'CATEGORY_LOADED',
    CATEGORY_DELETED:'CATEGORY_DELETED'
};